/* tslint:disable */
/* eslint-disable */
/**
 * Authority service openApi
 * API Docs
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface JWTRefresh
 */
export interface JWTRefresh {
    /**
     * Refresh token
     * @type {string}
     * @memberof JWTRefresh
     */
    'refreshToken': string;
}
/**
 * 
 * @export
 * @interface LoginParams
 */
export interface LoginParams {
    /**
     * Login
     * @type {string}
     * @memberof LoginParams
     */
    'login': string;
    /**
     * Session ID
     * @type {string}
     * @memberof LoginParams
     */
    'sessionId'?: string;
    /**
     * Password + login in md5 (in the example login - admin password - 12345678 md5sum(admin12345678))
     * @type {string}
     * @memberof LoginParams
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface LogoutParams
 */
export interface LogoutParams {
    /**
     * Login
     * @type {string}
     * @memberof LogoutParams
     */
    'login': string;
    /**
     * Session ID
     * @type {string}
     * @memberof LogoutParams
     */
    'sessionId'?: string;
}
/**
 * 
 * @export
 * @interface RegisterUser
 */
export interface RegisterUser {
    /**
     * Login
     * @type {string}
     * @memberof RegisterUser
     */
    'login': string;
    /**
     * First name
     * @type {string}
     * @memberof RegisterUser
     */
    'firstName': string;
    /**
     * Last name
     * @type {string}
     * @memberof RegisterUser
     */
    'lastName': string;
    /**
     * Mail
     * @type {string}
     * @memberof RegisterUser
     */
    'email': string;
    /**
     * Password + login in md5
     * @type {string}
     * @memberof RegisterUser
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
    /**
     * Login
     * @type {string}
     * @memberof UserCreate
     */
    'login': string;
    /**
     * First name
     * @type {string}
     * @memberof UserCreate
     */
    'firstName': string;
    /**
     * Last name
     * @type {string}
     * @memberof UserCreate
     */
    'lastName': string;
    /**
     * Mail
     * @type {string}
     * @memberof UserCreate
     */
    'email': string;
    /**
     * Role
     * @type {string}
     * @memberof UserCreate
     */
    'role': UserCreateRoleEnum;
    /**
     * Locked - 1/unlocked - 0
     * @type {number}
     * @memberof UserCreate
     */
    'locked': number;
    /**
     * Password + login in md5
     * @type {string}
     * @memberof UserCreate
     */
    'password': string;
}

export const UserCreateRoleEnum = {
    Admin: 'admin',
    Operator: 'operator',
    Guest: 'guest'
} as const;

export type UserCreateRoleEnum = typeof UserCreateRoleEnum[keyof typeof UserCreateRoleEnum];

/**
 * 
 * @export
 * @interface UserItem
 */
export interface UserItem {
    /**
     * Login
     * @type {string}
     * @memberof UserItem
     */
    'login': string;
    /**
     * First name
     * @type {string}
     * @memberof UserItem
     */
    'firstName': string;
    /**
     * Last name
     * @type {string}
     * @memberof UserItem
     */
    'lastName': string;
    /**
     * Mail
     * @type {string}
     * @memberof UserItem
     */
    'email': string;
    /**
     * Role
     * @type {string}
     * @memberof UserItem
     */
    'role': UserItemRoleEnum;
    /**
     * Locked - 1/unlocked - 0
     * @type {number}
     * @memberof UserItem
     */
    'locked': number;
    /**
     * Creation time
     * @type {string}
     * @memberof UserItem
     */
    'createdAt'?: string;
    /**
     * Update time
     * @type {string}
     * @memberof UserItem
     */
    'updatedAt'?: string;
}

export const UserItemRoleEnum = {
    Admin: 'admin',
    Operator: 'operator',
    Guest: 'guest'
} as const;

export type UserItemRoleEnum = typeof UserItemRoleEnum[keyof typeof UserItemRoleEnum];

/**
 * 
 * @export
 * @interface UserList
 */
export interface UserList {
    /**
     * User list
     * @type {Array<UserItem>}
     * @memberof UserList
     */
    'items': Array<UserItem>;
    /**
     * Total users match the filter
     * @type {number}
     * @memberof UserList
     */
    'count': number;
}
/**
 * 
 * @export
 * @interface UserUpdate
 */
export interface UserUpdate {
    /**
     * First name
     * @type {string}
     * @memberof UserUpdate
     */
    'firstName'?: string;
    /**
     * Last name
     * @type {string}
     * @memberof UserUpdate
     */
    'lastName'?: string;
    /**
     * Mail
     * @type {string}
     * @memberof UserUpdate
     */
    'email'?: string;
    /**
     * Role
     * @type {string}
     * @memberof UserUpdate
     */
    'role'?: UserUpdateRoleEnum;
    /**
     * Locked - 1/unlocked - 0
     * @type {number}
     * @memberof UserUpdate
     */
    'locked'?: number;
    /**
     * Password + login in md5
     * @type {string}
     * @memberof UserUpdate
     */
    'password'?: string;
}

export const UserUpdateRoleEnum = {
    Admin: 'admin',
    Operator: 'operator',
    Guest: 'guest'
} as const;

export type UserUpdateRoleEnum = typeof UserUpdateRoleEnum[keyof typeof UserUpdateRoleEnum];


/**
 * AuthorizationApi - axios parameter creator
 * @export
 */
export const AuthorizationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Log in (access token is installed in the cookie server!!!)
         * @param {LoginParams} loginParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerLogin: async (loginParams: LoginParams, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginParams' is not null or undefined
            assertParamExists('authControllerLogin', 'loginParams', loginParams)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginParams, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Log out
         * @param {LogoutParams} logoutParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerLogout: async (logoutParams: LogoutParams, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'logoutParams' is not null or undefined
            assertParamExists('authControllerLogout', 'logoutParams', logoutParams)
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(logoutParams, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a new access token
         * @param {JWTRefresh} jWTRefresh 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerRefresh: async (jWTRefresh: JWTRefresh, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jWTRefresh' is not null or undefined
            assertParamExists('authControllerRefresh', 'jWTRefresh', jWTRefresh)
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(jWTRefresh, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get information about the user using an access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerWhoAmi: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthorizationApi - functional programming interface
 * @export
 */
export const AuthorizationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthorizationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Log in (access token is installed in the cookie server!!!)
         * @param {LoginParams} loginParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerLogin(loginParams: LoginParams, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JWTRefresh>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerLogin(loginParams, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Log out
         * @param {LogoutParams} logoutParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerLogout(logoutParams: LogoutParams, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerLogout(logoutParams, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get a new access token
         * @param {JWTRefresh} jWTRefresh 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerRefresh(jWTRefresh: JWTRefresh, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JWTRefresh>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerRefresh(jWTRefresh, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get information about the user using an access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerWhoAmi(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserItem>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerWhoAmi(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AuthorizationApi - factory interface
 * @export
 */
export const AuthorizationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthorizationApiFp(configuration)
    return {
        /**
         * 
         * @summary Log in (access token is installed in the cookie server!!!)
         * @param {LoginParams} loginParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerLogin(loginParams: LoginParams, options?: any): AxiosPromise<JWTRefresh> {
            return localVarFp.authControllerLogin(loginParams, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Log out
         * @param {LogoutParams} logoutParams 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerLogout(logoutParams: LogoutParams, options?: any): AxiosPromise<void> {
            return localVarFp.authControllerLogout(logoutParams, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a new access token
         * @param {JWTRefresh} jWTRefresh 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerRefresh(jWTRefresh: JWTRefresh, options?: any): AxiosPromise<JWTRefresh> {
            return localVarFp.authControllerRefresh(jWTRefresh, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get information about the user using an access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerWhoAmi(options?: any): AxiosPromise<UserItem> {
            return localVarFp.authControllerWhoAmi(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthorizationApi - object-oriented interface
 * @export
 * @class AuthorizationApi
 * @extends {BaseAPI}
 */
export class AuthorizationApi extends BaseAPI {
    /**
     * 
     * @summary Log in (access token is installed in the cookie server!!!)
     * @param {LoginParams} loginParams 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorizationApi
     */
    public authControllerLogin(loginParams: LoginParams, options?: AxiosRequestConfig) {
        return AuthorizationApiFp(this.configuration).authControllerLogin(loginParams, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Log out
     * @param {LogoutParams} logoutParams 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorizationApi
     */
    public authControllerLogout(logoutParams: LogoutParams, options?: AxiosRequestConfig) {
        return AuthorizationApiFp(this.configuration).authControllerLogout(logoutParams, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a new access token
     * @param {JWTRefresh} jWTRefresh 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorizationApi
     */
    public authControllerRefresh(jWTRefresh: JWTRefresh, options?: AxiosRequestConfig) {
        return AuthorizationApiFp(this.configuration).authControllerRefresh(jWTRefresh, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get information about the user using an access token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorizationApi
     */
    public authControllerWhoAmi(options?: AxiosRequestConfig) {
        return AuthorizationApiFp(this.configuration).authControllerWhoAmi(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserManagementApi - axios parameter creator
 * @export
 */
export const UserManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a user
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersControllerCreate: async (userCreate: UserCreate, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userCreate' is not null or undefined
            assertParamExists('usersControllerCreate', 'userCreate', userCreate)
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete user
         * @param {string} login Login
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersControllerDelete: async (login: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'login' is not null or undefined
            assertParamExists('usersControllerDelete', 'login', login)
            const localVarPath = `/users/{login}`
                .replace(`{${"login"}}`, encodeURIComponent(String(login)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get list of users
         * @param {number} limit Limit
         * @param {number} offset Offset
         * @param {string} [sort] Sort Column
         * @param {UsersControllerGetAllOrderEnum} [order] Sorting. Direction. \&quot;ASC\&quot; - direct, \&quot;DESC\&quot; - reverse.
         * @param {string} [search] Search string. Search by first name, last name, email
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersControllerGetAll: async (limit: number, offset: number, sort?: string, order?: UsersControllerGetAllOrderEnum, search?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'limit' is not null or undefined
            assertParamExists('usersControllerGetAll', 'limit', limit)
            // verify required parameter 'offset' is not null or undefined
            assertParamExists('usersControllerGetAll', 'offset', offset)
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register a new user
         * @param {RegisterUser} registerUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersControllerRegister: async (registerUser: RegisterUser, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerUser' is not null or undefined
            assertParamExists('usersControllerRegister', 'registerUser', registerUser)
            const localVarPath = `/users/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerUser, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Change user
         * @param {string} login Login
         * @param {UserUpdate} userUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersControllerUpdate: async (login: string, userUpdate: UserUpdate, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'login' is not null or undefined
            assertParamExists('usersControllerUpdate', 'login', login)
            // verify required parameter 'userUpdate' is not null or undefined
            assertParamExists('usersControllerUpdate', 'userUpdate', userUpdate)
            const localVarPath = `/users/{login}`
                .replace(`{${"login"}}`, encodeURIComponent(String(login)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserManagementApi - functional programming interface
 * @export
 */
export const UserManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a user
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersControllerCreate(userCreate: UserCreate, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersControllerCreate(userCreate, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete user
         * @param {string} login Login
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersControllerDelete(login: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersControllerDelete(login, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get list of users
         * @param {number} limit Limit
         * @param {number} offset Offset
         * @param {string} [sort] Sort Column
         * @param {UsersControllerGetAllOrderEnum} [order] Sorting. Direction. \&quot;ASC\&quot; - direct, \&quot;DESC\&quot; - reverse.
         * @param {string} [search] Search string. Search by first name, last name, email
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersControllerGetAll(limit: number, offset: number, sort?: string, order?: UsersControllerGetAllOrderEnum, search?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserList>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersControllerGetAll(limit, offset, sort, order, search, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Register a new user
         * @param {RegisterUser} registerUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersControllerRegister(registerUser: RegisterUser, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersControllerRegister(registerUser, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Change user
         * @param {string} login Login
         * @param {UserUpdate} userUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersControllerUpdate(login: string, userUpdate: UserUpdate, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersControllerUpdate(login, userUpdate, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UserManagementApi - factory interface
 * @export
 */
export const UserManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserManagementApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a user
         * @param {UserCreate} userCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersControllerCreate(userCreate: UserCreate, options?: any): AxiosPromise<void> {
            return localVarFp.usersControllerCreate(userCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete user
         * @param {string} login Login
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersControllerDelete(login: string, options?: any): AxiosPromise<void> {
            return localVarFp.usersControllerDelete(login, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get list of users
         * @param {number} limit Limit
         * @param {number} offset Offset
         * @param {string} [sort] Sort Column
         * @param {UsersControllerGetAllOrderEnum} [order] Sorting. Direction. \&quot;ASC\&quot; - direct, \&quot;DESC\&quot; - reverse.
         * @param {string} [search] Search string. Search by first name, last name, email
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersControllerGetAll(limit: number, offset: number, sort?: string, order?: UsersControllerGetAllOrderEnum, search?: string, options?: any): AxiosPromise<UserList> {
            return localVarFp.usersControllerGetAll(limit, offset, sort, order, search, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register a new user
         * @param {RegisterUser} registerUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersControllerRegister(registerUser: RegisterUser, options?: any): AxiosPromise<void> {
            return localVarFp.usersControllerRegister(registerUser, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Change user
         * @param {string} login Login
         * @param {UserUpdate} userUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersControllerUpdate(login: string, userUpdate: UserUpdate, options?: any): AxiosPromise<void> {
            return localVarFp.usersControllerUpdate(login, userUpdate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserManagementApi - object-oriented interface
 * @export
 * @class UserManagementApi
 * @extends {BaseAPI}
 */
export class UserManagementApi extends BaseAPI {
    /**
     * 
     * @summary Create a user
     * @param {UserCreate} userCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserManagementApi
     */
    public usersControllerCreate(userCreate: UserCreate, options?: AxiosRequestConfig) {
        return UserManagementApiFp(this.configuration).usersControllerCreate(userCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete user
     * @param {string} login Login
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserManagementApi
     */
    public usersControllerDelete(login: string, options?: AxiosRequestConfig) {
        return UserManagementApiFp(this.configuration).usersControllerDelete(login, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get list of users
     * @param {number} limit Limit
     * @param {number} offset Offset
     * @param {string} [sort] Sort Column
     * @param {UsersControllerGetAllOrderEnum} [order] Sorting. Direction. \&quot;ASC\&quot; - direct, \&quot;DESC\&quot; - reverse.
     * @param {string} [search] Search string. Search by first name, last name, email
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserManagementApi
     */
    public usersControllerGetAll(limit: number, offset: number, sort?: string, order?: UsersControllerGetAllOrderEnum, search?: string, options?: AxiosRequestConfig) {
        return UserManagementApiFp(this.configuration).usersControllerGetAll(limit, offset, sort, order, search, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register a new user
     * @param {RegisterUser} registerUser 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserManagementApi
     */
    public usersControllerRegister(registerUser: RegisterUser, options?: AxiosRequestConfig) {
        return UserManagementApiFp(this.configuration).usersControllerRegister(registerUser, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Change user
     * @param {string} login Login
     * @param {UserUpdate} userUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserManagementApi
     */
    public usersControllerUpdate(login: string, userUpdate: UserUpdate, options?: AxiosRequestConfig) {
        return UserManagementApiFp(this.configuration).usersControllerUpdate(login, userUpdate, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const UsersControllerGetAllOrderEnum = {
    Asc: 'ASC',
    Desc: 'DESC'
} as const;
export type UsersControllerGetAllOrderEnum = typeof UsersControllerGetAllOrderEnum[keyof typeof UsersControllerGetAllOrderEnum];


